#!/bin/bash
yad --title="Conky" --width=300 --window-icon="/usr/share/miyolinux/icons/miyolinux.png" --text-align=center --center --buttons-layout="center" --text="
Temporarily turn the Conky On or Off.
" \
--button="On":"conky" \
--button="Off":"killall conky" \
